# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TourPlanner
                                 A QGIS plugin
 A modular plugin for developing, comparing, and extending various tour and route planning algorithms.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-08
        copyright            : (C) 2026 by Philipp von Kirschbaum
        email                : philipp@vonkirschbaum.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TourPlanner class from file TourPlanner.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    try:
        import geopandas as gpd
    except ImportError:
        iface.messageBar().pushCritical(
            "Plugin",
            "GeoPandas fehlt. Siehe Plugin-Dokumentation zur Installation."
        )

    from .tour_planner import TourPlanner
    return TourPlanner(iface)
