# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TourPlanner
                                 A QGIS plugin
 A modular plugin for developing, comparing, and extending various tour and route planning algorithms.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-08
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Philipp von Kirschbaum
        email                : philipp@vonkirschbaum.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QVariant
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QAbstractItemView, QTableWidgetItem, QComboBox, QMessageBox
from qgis.core import QgsMapLayerProxyModel, QgsVectorLayer, QgsProject, QgsFeature, QgsGeometry, QgsVectorFileWriter, QgsField

import importlib.util
import sys

import numpy as np
import pandas as pd
import geopandas as gpd
import tempfile
import os
import requests
import json
from urllib.parse import quote
import tempfile
import pickle
import subprocess


# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .tour_planner_dialog import TourPlannerDialog
import os.path


class TourPlanner:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'TourPlanner_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&TourPlanner')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        self.depots_gdf = None
        self.vehiles_df = None
        self.tours_gdf = None
        self.matrix_depot_to_start = None
        self.matrix_end_to_depot = None
        self.matrix_tours_to_tours = None
        self.valhalla_url = ''

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('TourPlanner', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/tour_planner/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'TourPlanner'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&TourPlanner'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.init_dialog()


        # clear Dialog and data
        self.depots_gdf = None
        self.vehiles_df = None
        self.tours_gdf = None
        self.matrix_depot_to_start = None
        self.matrix_end_to_depot = None
        self.matrix_tours_to_tours = None
        self.valhalla_url = ''
        
        self.dlg.tableWidgetData.setItem(0, 1, QTableWidgetItem("0"))
        self.dlg.tableWidgetData.setItem(1, 1, QTableWidgetItem("0"))
        self.dlg.tableWidgetData.setItem(2, 1, QTableWidgetItem("0"))
        self.dlg.tableWidgetData.setItem(3, 1, QTableWidgetItem("0"))
        self.dlg.tabWidget.setTabEnabled(1, False)
        self.dlg.tabWidget.setCurrentIndex(0)
        self.dlg.cbDebug.setChecked(False)
        # TODO reset inputs
        
        
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    def init_dialog(self):
        self.dlg = TourPlannerDialog()
        # Filter für Layer
        self.dlg.mapLayerDepots.setFilters(QgsMapLayerProxyModel.PointLayer)
        self.dlg.mapLayerVehicles.setFilters(QgsMapLayerProxyModel.NoGeometry)
        self.dlg.mapLayerTours.setFilters(QgsMapLayerProxyModel.LineLayer)
        # Dateifilter
        self.dlg.fileDialogSkript.setFilter("Python (*.py)")
        # TODO REMOVE in PRODUCTION
        self.dlg.fileDialogSkript.setFilePath("/Users/philipp/Git/GitLab-privat/bd/ktp-platform/science/routing_scripts/test.py")
        self.dlg.fileDialogOutput.setFilePath("/Users/philipp/Git/GitLab-privat/bd/ktp-platform/science/routing_scripts/output")
        self.dlg.fileDialogVenv.setFilePath("/Users/philipp/anaconda3/envs/ktp-science/bin/python3")

        self.dlg.tableWidgetData.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.dlg.tableWidgetData.setHorizontalHeaderLabels(["Daten","Anzahl"])
        self.dlg.tableWidgetData.setRowCount(3)
        self.dlg.tableWidgetData.setItem(0, 0, QTableWidgetItem("Depots"))
        self.dlg.tableWidgetData.setItem(1, 0, QTableWidgetItem("Fahrzeuge"))
        self.dlg.tableWidgetData.setItem(2, 0, QTableWidgetItem("Touren"))
        
        self.dlg.tableWidgetSkriptParam.setHorizontalHeaderLabels(["Parameter","Wert", "Typ"])
        
        self.dlg.pushButtonParamAdd.clicked.connect(self.add_param_row)
        self.dlg.pushButtonParamDelete.clicked.connect(self.delete_param_row)

        self.dlg.buttonSelectData.clicked.connect(self.selectData)
        self.dlg.pushButtonRun.clicked.connect(self.run_script)
        pass
    
    def add_param_row(self):
        row = self.dlg.tableWidgetSkriptParam.rowCount()
        self.dlg.tableWidgetSkriptParam.insertRow(row)

        self.dlg.tableWidgetSkriptParam.setItem(row, 0, QTableWidgetItem("1"))
        self.dlg.tableWidgetSkriptParam.setItem(row, 1, QTableWidgetItem(""))

        # Dropdown
        combo = QComboBox()
        combo.addItems(["String", "Integer", "Float", "Boolean"])
        self.dlg.tableWidgetSkriptParam.setCellWidget(row, 2, combo)
        pass

    def delete_param_row(self):
        row = self.dlg.tableWidgetSkriptParam.currentRow()
        if row >= 0:
            self.dlg.tableWidgetSkriptParam.removeRow(row)
        pass

    def selectData(self):
        file_path = self.dlg.fileDialogSkript.filePath()
        if file_path == None or file_path == "":
            self.iface.messageBar().pushCritical(
                "Plugin",
                "Kein Skript ausgewählt"
            )
            return
        
        python_file_path = self.dlg.fileDialogVenv.filePath()
        if python_file_path == None or python_file_path == "":
            self.iface.messageBar().pushCritical(
                "Plugin",
                "Keine Python-Umgebung ausgewählt"
            )
            return
        
        output_path = self.dlg.fileDialogOutput.filePath()
        if output_path == None or output_path == "":
            self.iface.messageBar().pushCritical(
                "Plugin",
                "Kein Ausgabe-Ordner ausgewählt"
            )
            return
        
        depots_layer = self.dlg.mapLayerDepots.currentLayer()
        if not depots_layer:
            self.iface.messageBar().pushCritical(
                "Plugin",
                "Kein gültiger Vektorlayer ausgewählt für Depots"
            )
            return
        vehicle_layer = self.dlg.mapLayerVehicles.currentLayer()
        if not vehicle_layer:
            self.iface.messageBar().pushCritical(
                "Plugin",
                "Kein gültiger Layer ausgewählt für Fahrzeuge"
            )
            return
        tour_layer = self.dlg.mapLayerTours.currentLayer()
        if not tour_layer:
            self.iface.messageBar().pushCritical(
                "Plugin",
                "Kein gültiger Layer ausgewählt für Touren"
            )
            return
        
        self.valhalla_url = self.dlg.leValhalla.text()        

        self.read_depots()
        self.read_vehicles()
        self.read_tours()

        self.calc_depots_cost_matrix()
        self.calc_tours_cost_matrix()
        self.calc_tours_cost()
        
        self.dlg.tableWidgetData.setItem(0, 1, QTableWidgetItem(str(len(self.depots_gdf.index))))
        self.dlg.tableWidgetData.setItem(1, 1, QTableWidgetItem(str(len(self.vehiles_df.index))))
        self.dlg.tableWidgetData.setItem(2, 1, QTableWidgetItem(str(len(self.tours_gdf.index))))
        self.dlg.tabWidget.setTabEnabled(1, True)
        self.dlg.tabWidget.setCurrentIndex(1)
        pass

    def read_depots(self):
        depots_layer = self.dlg.mapLayerDepots.currentLayer()

        tmp_dir = tempfile.mkdtemp()
        tmp_path = os.path.join(tmp_dir, "input.gpkg")

        QgsVectorFileWriter.writeAsVectorFormat(
            depots_layer,
            tmp_path,
            "UTF-8",
            depots_layer.crs(),
            "GPKG"
        )

        self.depots_gdf = gpd.read_file(tmp_path)
        pass

    def read_vehicles(self):
        layer = self.dlg.mapLayerVehicles.currentLayer()

        fields = [field.name() for field in layer.fields()]
        rows = []

        for feature in layer.getFeatures():
            rows.append(feature.attributes())

        self.vehiles_df = pd.DataFrame(rows, columns=fields)
        pass

    def read_tours(self):
        tours_layer = self.dlg.mapLayerTours.currentLayer()

        tmp_dir = tempfile.mkdtemp()
        tmp_path = os.path.join(tmp_dir, "input.gpkg")

        QgsVectorFileWriter.writeAsVectorFormat(
            tours_layer,
            tmp_path,
            "UTF-8",
            tours_layer.crs(),
            "GPKG"
        )

        self.tours_gdf = gpd.read_file(tmp_path)
        pass
    
    def _get_valhalla_matrix_param(self, sources, targets, costing):
        data = {"sources":sources,"targets":targets,"costing":costing}
        return quote(json.dumps(data, default=str))
    
    def parse_valhalla_to_df(self, data, row_labels, col_labels):
        # Erstellt eine 2D-Liste der Distanzen
        matrix = [
            [target['time'] for target in source] 
            for source in data['sources_to_targets']
        ]
        return pd.DataFrame(matrix, index=row_labels, columns=col_labels)
    
    def calc_depots_cost_matrix(self):
        depots_coords = [
            {"lat": geom.y, "lon": geom.x} 
            for geom in self.depots_gdf.geometry
        ]
        
        tours_start = []
        for geom in self.tours_gdf.geometry:
            if geom is None or geom.is_empty:
                continue
            if geom.geom_type == 'MultiLineString':
                # Nimm die erste Linie aus der Sammlung
                first_part = geom.geoms[0]
                lon, lat = first_part.coords[0]
                tours_start.append({"lat": lat, "lon": lon, "radius": 100})
            elif geom.geom_type == 'LineString':
                # Direkter Zugriff bei einfacher Linie
                lon, lat = geom.coords[0]
                tours_start.append({"lat": lat, "lon": lon, "radius": 100})
        
        tours_end = []
        for geom in self.tours_gdf.geometry:
            if geom is None or geom.is_empty:
                continue
            if geom.geom_type == 'MultiLineString':
                # Nimm die erste Linie aus der Sammlung
                first_part = geom.geoms[-1]
                lon, lat = first_part.coords[-1]
                tours_end.append({"lat": lat, "lon": lon, "radius": 100})
            elif geom.geom_type == 'LineString':
                # Direkter Zugriff bei einfacher Linie
                lon, lat = geom.coords[-1]
                tours_end.append({"lat": lat, "lon": lon, "radius": 100})
        
        # Kosten von Depots zu Transport-Starts berechnenen
        url = self.valhalla_url + '/sources_to_targets?json=' + self._get_valhalla_matrix_param(depots_coords,tours_start, "auto")
        response_start = requests.get(url)
        response_start.raise_for_status()
        start_data = response_start.json()
        
        # Kosten von Transport-Stops zu Depots berechnenen
        url = self.valhalla_url + '/sources_to_targets?json=' + self._get_valhalla_matrix_param(tours_end,depots_coords, "auto")
        response_end = requests.get(url)
        response_end.raise_for_status()
        end_data = response_end.json()
        
        # In Datenmodell überführen
        
        depot_ids = self.depots_gdf['id'].tolist()
        tour_ids = self.tours_gdf['id'].tolist()
        
        # Matrix: Zeilen = Depots, Spalten = Touren
        self.matrix_depot_to_start = self.parse_valhalla_to_df(start_data, depot_ids, tour_ids)

        # Matrix: Zeilen = Touren, Spalten = Depots
        self.matrix_end_to_depot = self.parse_valhalla_to_df(end_data, tour_ids, depot_ids)
        pass
    
    def calc_tours_cost_matrix(self):
        valid_indices = []
        tours_start = []
        tours_end = []
        
        for idx, geom in self.tours_gdf.geometry.items():
            if geom is None or geom.is_empty:
                continue
            
            if geom.geom_type == 'MultiLineString':
                # Startpunkt (erste Linie, erster Punkt)
                start_lon, start_lat = geom.geoms[0].coords[0]
                # Endpunkt (letzte Linie, letzter Punkt)
                end_lon, end_lat = geom.geoms[-1].coords[-1]
            elif geom.geom_type == 'LineString':
                start_lon, start_lat = geom.coords[0]
                end_lon, end_lat = geom.coords[-1]
            else:
                continue
            
            tours_start.append({"lat": start_lat, "lon": start_lon, "radius": 100})
            tours_end.append({"lat": end_lat, "lon": end_lon, "radius": 100})
            valid_indices.append(self.tours_gdf.loc[idx, "id"]) # Wir merken uns den Original-Index der Tour!
        
        # Abbruch, falls keine validen Touren gefunden wurden
        if not valid_indices:
            raise "No valid tours found"
        
        # 2. Valhalla API Aufruf
        # Quellen = tours_end (Ende der vorherigen Tour)
        # Ziele = tours_start (Start der nächsten Tour)
        url = f"{self.valhalla_url}/sources_to_targets?json={self._get_valhalla_matrix_param(tours_end, tours_start, 'auto')}"
        
        try:
            response_tour = requests.get(url)
            response_tour.raise_for_status()
            tours_data = response_tour.json()
        except requests.exceptions.RequestException as e:
            print(f"Fehler bei der Valhalla Matrix-Berechnung: {e}")
            raise e
        
        
        # 3. Zeit und Strecke in ein kombiniertes DataFrame schreiben
        matrix_data = tours_data.get('sources_to_targets', [])

        verbindungen = []

        for i, row in enumerate(matrix_data):
            von_tour_id = valid_indices[i]
            
            for j, cell in enumerate(row):
                nach_tour_id = valid_indices[j]
                
                # Zeit und Distanz auslesen
                fahrzeit = cell.get('time')
                strecke = cell.get('distance')
                
                verbindungen.append({
                    'start_tour_id': von_tour_id,
                    'end_tour_id': nach_tour_id,
                    'time': fahrzeit,
                    'distance': strecke
                })

        matrix_df = pd.DataFrame(verbindungen)

        # Einträge mit gleicher tour_id herausfiltern
        matrix_df = matrix_df[matrix_df['start_tour_id'] != matrix_df['end_tour_id']].reset_index(drop=True)

        self.matrix_tours_to_tours = matrix_df
        pass
    
    def fetch_valhalla_route_info(self, geom, valhalla_url):
    # Null-Werte abfangen
        if geom is None or geom.is_empty:
            return pd.Series([None, None])
            
        start = None
        end = None
        
        # Koordinaten extrahieren
        if geom.geom_type == 'MultiLineString':
            first_part = geom.geoms[0]
            lon_start, lat_start = first_part.coords[0]
            lon_end, lat_end = first_part.coords[-1]
            start = {"lat": lat_start, "lon": lon_start, "radius": 100}
            end = {"lat": lat_end, "lon": lon_end, "radius": 100}
        elif geom.geom_type == 'LineString':
            lon_start, lat_start = geom.coords[0]
            lon_end, lat_end = geom.coords[-1]
            start = {"lat": lat_start, "lon": lon_start, "radius": 100}
            end = {"lat": lat_end, "lon": lon_end, "radius": 100}
            
        if start is None or end is None:
            return pd.Series([None, None])
            
        # Valhalla Request vorbereiten
        data = {"locations": [start, end], "costing": "auto"}
        data_param = quote(json.dumps(data, default=str))
        url = f"{valhalla_url}/route?json={data_param}"
        
        try:
            response_tour = requests.get(url)
            response_tour.raise_for_status()
            tour_data = response_tour.json()
            
            # Daten aus Valhalla extrahieren (Einheiten: length in km, time in s)
            summary = tour_data.get('trip', {}).get('summary', {})
            distance = summary.get('length')
            time = summary.get('time')
            
            return pd.Series([distance, time])
            
        except requests.exceptions.RequestException as e:
            print(f"API Fehler bei Koordinaten {start} zu {end}: {e}")
            return pd.Series([None, None])
        
    def calc_tours_cost(self):
        self.tours_gdf[['distance_km', 'time_sec']] = self.tours_gdf.geometry.apply(
            lambda geom: self.fetch_valhalla_route_info(geom, self.valhalla_url)
        )
        pass

    def run_script(self):
        file_path = self.dlg.fileDialogSkript.filePath()
        python_file_path = self.dlg.fileDialogVenv.filePath()
        
        # spec = importlib.util.spec_from_file_location("external_script", file_path)
        # module = importlib.util.module_from_spec(spec)
        # sys.modules["external_script"] = module
        # spec.loader.exec_module(module)

        # Zusatzparameter hinzufügen
        extra_params = {}
        for row in range(self.dlg.tableWidgetSkriptParam.rowCount()):
            key_item = self.dlg.tableWidgetSkriptParam.item(row, 0)
            val_item = self.dlg.tableWidgetSkriptParam.item(row, 1)
            if key_item is not None and val_item is not None:
                type_combo = self.dlg.tableWidgetSkriptParam.cellWidget(row, 2)
                
                if key_item is not None and val_item is not None and type_combo is not None:
                    key = key_item.text().strip()
                    val_str = val_item.text().strip()
                    
                    # Ausgewählten Datentyp aus der ComboBox auslesen
                    val_type = type_combo.currentText()
                    
                    if not key:
                        continue
                        
                    # Wert basierend auf der ComboBox konvertieren
                    try:
                        if val_type == "String":
                            final_value = val_str
                        elif val_type == "Integer":
                            final_value = int(val_str)
                        elif val_type == "Float":
                            final_value = float(val_str.replace(',', '.'))
                        elif val_type == "Boolean":
                            # Typische "Wahr"-Werte abfangen
                            final_value = val_str.lower() in ['true', 'wahr', '1', 'ja', 'yes']
                        else:
                            final_value = val_str # Fallback
                        
                        extra_params[key] = final_value
                        
                    except ValueError:
                        # TODO ordentliche Warnung anzeigen
                        print(f"Warnung: Konnte den Wert '{val_str}' für Parameter '{key}' nicht in {val_type} umwandeln. Wird übersprungen.")
        if self.dlg.cbDebug.isChecked():
            self.save_debug_data()
        
        try:
            #resp = module.calculate(
            #    depots=self.depots_gdf,
            #    vehicles= self.vehiles_df,
            #    tours=self.tours_gdf,
            #    matrix_depots_starts=self.matrix_depot_to_start,
            #    matrix_ends_depots=self.matrix_end_to_depot,
            #    matrix_tours_to_tours=self.matrix_tours_to_tours,
            #    valhalla_url=self.valhalla_url,
            #    **extra_params)
            
            # Daten für den Transfer vorbereiten
            input_data = {
                "depots": self.depots_gdf,
                "vehicles": self.vehiles_df,
                "tours": self.tours_gdf,
                "matrix_depots_starts": self.matrix_depot_to_start,
                "matrix_ends_depots": self.matrix_end_to_depot,
                "matrix_tours_to_tours": self.matrix_tours_to_tours,
                "valhalla_url": self.valhalla_url,
                "extra_params": extra_params
            }
            
            # 3. Temporäre Dateien für Input und Output erstellen
            with tempfile.NamedTemporaryFile(delete=False, suffix=".pkl") as f_in, \
                tempfile.NamedTemporaryFile(delete=False, suffix=".pkl") as f_out:
                
                input_file = f_in.name
                output_file = f_out.name
                
                # Daten serialisieren
                pickle.dump(input_data, f_in)

                    
            # 4. Wrapper-Aufruf vorbereiten
            # Wir rufen ein kleines Hilfsskript auf, das die venv-Umgebung nutzt
            try:
                # Wir übergeben dem Skript die Pfade zu den Temp-Dateien
                result = subprocess.run(
                    [python_file_path, file_path, input_file, output_file],
                    capture_output=True,
                    text=True,
                    check=True
                )

                # 5. Rückgabe laden
                if os.path.exists(output_file):
                    resp = gpd.read_file(output_file)
                    
                    # Temporäres Layer erstellen
                    self.create_memory_layer(resp)
                
            except subprocess.CalledProcessError as e:
                print(e)
                QMessageBox.critical(self.iface.mainWindow(), "Script Error", f"Fehler im Python-Skript:\n{e.stderr}")
            except Exception as e:
                print(e)
                QMessageBox.critical(self.iface.mainWindow(), "Error", str(e))
            finally:
                # Aufräumen
                if os.path.exists(input_file): os.remove(input_file)
                if os.path.exists(output_file): os.remove(output_file)        
        except Exception as e:
            QMessageBox.critical(self.iface.mainWindow(), "Script Error", str(e))
        pass
    
    def save_debug_data(self):
        output_path = self.dlg.fileDialogOutput.filePath()
        
        self.depots_gdf.to_file(output_path + '/depots.shp')
        self.vehiles_df.to_csv(output_path + '/vehicles.csv')
        self.tours_gdf.to_file(output_path + '/tours.shp')
        self.matrix_depot_to_start.to_csv(output_path + '/matrix_depots_to_starts.csv')
        self.matrix_end_to_depot.to_csv(output_path + '/matrix_ends_to_depots.csv')
        self.matrix_tours_to_tours.to_csv(output_path + '/matrix_tours_to_tours.csv')
        pass

    def create_memory_layer(self, gdf, layer_name="Touren"):
        # 1. Geometrietyp und EPSG aus dem GDF auslesen
        geom_type = gdf.geom_type.iloc[0] # 'Point', 'LineString', 'Polygon'
        epsg = gdf.crs.to_epsg()
        
        # 2. Leeres Memory-Layer anlegen
        uri = f"{geom_type}?crs=epsg:{epsg}"
        layer = QgsVectorLayer(uri, layer_name, "memory")
        pr = layer.dataProvider()
        
        geom_col_name = gdf.geometry.name
        attribute_columns = [col for col in gdf.columns if col != geom_col_name]
        
        # 3. Datentypen mappen und QGIS-Felder anlegen
        qgs_fields = []
        for col in attribute_columns:
            dtype = gdf[col].dtype
            
            # Pandas Datentypen zu PyQt QVariant mappen
            if pd.api.types.is_integer_dtype(dtype):
                qtype = QVariant.Int
            elif pd.api.types.is_float_dtype(dtype):
                qtype = QVariant.Double
            elif pd.api.types.is_bool_dtype(dtype):
                qtype = QVariant.Bool
            elif pd.api.types.is_datetime64_any_dtype(dtype):
                qtype = QVariant.DateTime
            else:
                qtype = QVariant.String # Standard-Fallback
                
            qgs_fields.append(QgsField(str(col), qtype))
            
        # Felder dem Layer hinzufügen
        pr.addAttributes(qgs_fields)
        layer.updateFields() # Wichtig: Damit das Layer die neuen Felder "kennt"
        
        # 4. Features bauen (Geometrie als WKT übergeben)
        features = []
        for idx, row in gdf.iterrows():
            feat = QgsFeature()
            # shapely Geometrie zu WKT, dann zu QgsGeometry
            geom_wkt = row.geometry.wkt 
            feat.setGeometry(QgsGeometry.fromWkt(geom_wkt))
            
            # Attribute anhängen
            attrs = []
            for col in attribute_columns:
                val = row[col]
                
                # Fehlende Werte (NaN/None) als NULL an QGIS übergeben
                if pd.isna(val):
                    attrs.append(None)
                # NumPy Typen sicher in native Python Typen casten (QGIS mag oft keine np.int64)
                elif isinstance(val, (np.integer, int)):
                    attrs.append(int(val))
                elif isinstance(val, (np.floating, float)):
                    attrs.append(float(val))
                else:
                    attrs.append(str(val))
                    
            feat.setAttributes(attrs)
            features.append(feat)
            
        # 5. Features zum Layer hinzufügen und updaten
        pr.addFeatures(features)
        layer.updateExtents()
        
        QgsProject.instance().addMapLayer(layer)
        return layer